backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: shows
    label: Shows
    label_singular: Show
    folder: src/cms/markdown/shows
    create: true
    slug: "/{{title}}"
    fields:
      - widget: hidden
        name: templateKey
        label: Template Key
        default: show
      - widget: string
        name: title
        label: Title
        required: true
        hint: >-
          The title of the show, used for the /subfolder on the site and campaign id
      - widget: boolean
        name: research
        default: false
        label: Custom Research Microsite Link
        hint: >-
          Whether to use show Title for links to eisaioncologyresearch
      - widget: relation
        name: link
        label: Link
        required: true
        multiple: true
        hint: >-
          The links visible for the show
        collection: links
        valueField: title
        searchFields: ["title"]
        displayFields: ["title"]
  - name: links
    label: Links
    label_singular: Link
    folder: src/cms/markdown/links
    create: true
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: >-
          Unique name for the link
      - widget: markdown
        name: label
        label: Label
        required: true
        hint: >-
          Visual text label on the site
      - widget: string
        name: url
        label: URL
        required: true
        hint: >-
          HTTP url target for link
